# Generated by Django 4.2.4 on 2023-08-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('MUSEUM', '박물관'), ('ART GALLERY', '미술관'), ('EXHIBITION', '전시회')], max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('has_accessible_toilet', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
            ],
        ),
    ]
