# Generated by Django 4.2.4 on 2023-08-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.FloatField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.facility')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.station')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('path_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='path.path')),
            ],
        ),
    ]
