# Generated by Django 4.2.4 on 2023-08-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('distance', models.FloatField()),
                ('duration', models.DurationField()),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.facility')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_paths', to='place.station')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('path_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='path.path')),
            ],
        ),
    ]
