# Generated by Django 4.2.4 on 2023-08-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placeinfo', '0001_initial'),
        ('obstacle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duration', models.DurationField()),
                ('end_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeinfo.place')),
                ('obstacles', models.ManyToManyField(blank=True, to='obstacle.obstacle')),
                ('start_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_paths', to='placeinfo.place')),
            ],
        ),
    ]
