# Generated by Django 4.2.4 on 2023-08-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('path', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=30)),
                ('rating', models.PositiveIntegerField(blank=True, default=0, help_text='별 개수 (0 ~ 5)', null=True)),
                ('comment', models.TextField()),
                ('path_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='path.path')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
