# Generated by Django 4.2.4 on 2023-08-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('museum', '박물관'), ('artGallery', '미술관'), ('exhibition', '전시회')], max_length=20)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('opening_time', models.CharField(max_length=10)),
                ('closing_time', models.CharField(max_length=10)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('imageSrc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('line', models.IntegerField()),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('fac_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.facility')),
            ],
        ),
        migrations.CreateModel(
            name='StatAmenity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default='1')),
                ('stat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.station')),
            ],
        ),
        migrations.CreateModel(
            name='FacAmenity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default='1')),
                ('fac_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.facility')),
            ],
        ),
    ]
