# Generated by Django 4.2.4 on 2023-08-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_amenity_quantity_alter_facility_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacAmenity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default='1')),
                ('fac_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.facility')),
            ],
        ),
        migrations.CreateModel(
            name='StatAmenity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default='1')),
                ('stat_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.station')),
            ],
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
