# Generated by Django 4.2.4 on 2023-08-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('path', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObsType',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='osbImage')),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('explanation', models.TextField()),
                ('path_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='path.path')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obstacle.obstype')),
            ],
        ),
    ]
