# Generated by Django 4.2.4 on 2023-08-17 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('path', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObsType',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='./obstacle/obsIcon')),
            ],
        ),
        migrations.CreateModel(
            name='Obstacle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('path_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='path.path')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obstacle.obstype')),
            ],
        ),
    ]
