# Generated by Django 4.2.4 on 2023-08-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstacle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstacle',
            name='explanation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='obstacle',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='obstype',
            name='icon',
            field=models.ImageField(upload_to='./obstacle/obsIcon'),
        ),
    ]
