# Generated by Django 4.2.4 on 2023-08-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obstacle', '0002_alter_obstacle_explanation_alter_obstacle_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obstacle',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
